ARG version
FROM almalinux:${version:-6}
ARG sudheer=topper
ARG vineela=duller
RUN echo "sudheer is ${sudheer} and vineela is ${vineela} "
CMD [ "sleep", "100" ]


# How can you check version of your OS? cat /etc/*release