ARG version
FROM almalinux:${version}
ARG sudheer
ARG vineela
RUN echo "sudheer is ${sudheer} and vineela is ${vineela} "
CMD [ "sleep", "100" ]


# How can you check version of your OS? cat /etc/*release